export default { 
		"grom": {
			title: 'Błękitny Grom',
			description: 'Błękitny Grom" is annual adventure race, organised by 14th Scout Troops from Poznań. Every year race takes place in different forest area in Poland. Competitors have to swim, run and cycle the route which couts around 80km. They start in 4-person teams at 6 am, and end in various times, but the last team usually comes to the finish about 10pm. Terrain is difficult, there is number of so called special task - like climbing, shooting to target, quads or logical puzzles.\n\nThe photoessay was created with collaboration with Maria Obiębska, Jakub Piskorski and Zuzanna Dominikowska\n\nRace took place in march 2016',
			imagesDir: 'grom/',
			photos: [
				"Ian Sowinski",
				"Ian Sowinski",
				"Ian Sowinski",
				"Ian Sowinski",
				"Zuzanna Dominikowska",
				"Ian Sowinski",
				"Jakub Piskorski",
				"Ian Sowinski",
				"Jakub Piskorski",
				"Maria Obrębska",
				"Jakub Piskorski",
				"Zuzanna Dominikowska",
				"Maria Obrębska",
				"Zuzanna Dominikowska",
				"Maria Obrębska",
				"Maria Obrębska",
				"Maria Obrębska",
				"Maria Obrębska",
				"Maria Obrębska",
				"Maria Obrębska"
			]
		},
		"kod": {
			title: 'Anti-government protest in Warsaw',
			description: '2015 ellections in Poland was great succes of Law and Justice party - conservative and socialist party, rulled by Jarosław Kaczyński. We did\'nt have to wait long for the moment, when neo-liberal communities around Poland started organising anti-government protests.\n\nI decided to photograph one of this protests, propably one of the biggest, which took place in Warsaw on may 2015.',
			imagesDir: 'kod/',
			photos: [
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				""
			]
		},
		"endless-summer": {
			title: 'Endless Summer',
			description: 'Polish scouts spends about one month a year in forest or in travel. Relations between them are usually much deeper than betwen most school-focused social groups. Living in forest and working together to build a camp from scratch (and they do so every year), brings them closer and gives them a lot of common adventures. It is very unique society for witch tradition is very important. Scouting is considered by them as not only the alternative system of education, but also as the way of living.\n\nTalking with people who used to be scouts, I usually hear that values witch they developed in scouting teams, such as: friendship, helpfulness and responsibility are still very important for them. And the bond between generations are very similar to those tribal concept of older, wise people being guides to younger generation.\n\nWhen a lot of traveling photographers go to jungle to search for people living in very primitive way, it is very easy to find such people in Polish forests every summer. A lot of scouting teams decide resign from number of comforts that civilization is giving them every year, and decide to live without power supply, hot showers and central heating for a few weeks. This romantic idea leads to creation of micro-world where young people try to find true values of living. \n\n(2010-2016)',
			imagesDir: 'endless-summer/',
			photos: [
				"2013, building the scouting camp",
				"2014, boy scouts after holly mass",
				"2011, game in forest",
				"2009, author unknown",
				"2014, cross build by scouts during camp",
				"2015, packing equipment for the camp in forest",
				"2014, scouting game",
				"2015, bathroom tent on the scouting camp",
				"2014, role playing game at night",
				"2015, boy scouts on the top of camp's tower build by them",
				"2012, trekking in Sudety mountains",
				"2014, congress of the oldest scouting teams in Poland",
				"2014, scouting senior",
				"2013, portrait od Ania",
				"2015, having fun on the weekend camp",
				"2013, dinner on scouting camp",
				"2015, boy scouts fighting for fun",
				"2015, muster on scouting camp",
				"2015, troops flags",
				"2015, ceremony by the fire",
				"2016 - Singing by the fireplace",
				"2014, tribute to the veterans",
				"2015 - flag ceremony after camp",
				"2015, ending the scouting camp and removing the national ",
				"2016, overexposured portrait of Maria",
				"2012, boyscouts hats",
				"2015, prepering to the walk",
				"2013, first morning flag ceremony"
			]
		},
		"east-meets-east": {
			title: 'East meets East',
			description: 'After quarter of century, after fall of communism in Eurpe, echo of the past events still bounces off monuments and people. Even though it\'s nearly impossible to find Lenin in Poland, in neighboring Belarus you\'ll find him in every small town. While on russian countryside, bloody dictator is hanging on the wall alongside with Mary the Virgin, in center of Kiev killed by Berkut freedom fighters are comemorated by portraits, flowers and candles. While on Ukraine flag of European Union is flutters alongside to national colors, in front of Bunderstag you can find Ribbon of Saint George and Russian Federation flag. \n\nOn one border, we had The Wall, on other one - endless forests of taiga. A lot of things unites us, and a lot devides us. Everybody gone their own road, Eastern Europeans state of minds will stay for decades different from mentality of our western friends. \n\n(2011-present)',
			imagesDir: 'east-meets-east/',
			photos: [
				"Germany, 2015",
				"Belarus, 2011",
				"Germany, 2015",
				"Russia, 2012",
				"Ukraine, 2015",
				"Ukraine, 2015",
				"Poland, 2015",
				"Ukraine, 2015",
				"Croatia, 2014",
				"Russia, 2012",
				"Poland, 2015",
				"Ukraine, 2015",
				"Ukraine, 2015",
				"Russia, 2012",
				"Ukraine, 2015",
				"Ukraine, 2015",
				"Croatia, 2014",
				"Ukraine, 2015",
				"Ukraine, 2015",
				"Poland, 2014",
				"Belarus, 2011"
			]
		},
		"tymek-and-jagoda": {
			title: 'Wedding',
			description: 'Tymek and Jagoda are my friends from scouting, they invited me to their wedding, so it would be a shame not to take a camera with me - presented reportage is from the guest\'s point of view.',
			imagesDir: 'tymek-and-jagoda/',
			photos: [
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				""
			]
		},
		"presence": {
			title: 'Presence ',
			description: '',
			imagesDir: 'presence/',
			photos: [
				"Rennes, France - 2016",
				"Bieszczady, Poland - 2015",
				"Poznań, Poland - 2015",
				"Chojnice, Poland - 2015",
				"West Highland Way, Scotland - 2015",
				"Poznań, Poland - 2015",
				"West Highland Way, Scotland - 2015",
				"Kovel, Ukraine - 2015",
				"Poznań, Poland - 2015",
				"Rennes, France - 2016",
				"Paris, France - 2016",
				"Grenoble, France - 2016",
				"Highway, France - 2016",
				"Berlin, Germany - 2016",
				"Chomiąża Szlachecka, Poland - 2016",
				"Puszcza Zielonka, Poland - 2016",
				"London, England - 2016",
				"Jerusalem, Israel - 2016",
				"Tel Aviv, Israel - 2016",
				"Lublin, Poland - 2015"
			]
		},
		"argument-against-the-divinity-of-men": {
			title: 'Argument against the divinity of men',
			description: 'Czesław Miłosz\nIN VAIN\n\nEither gods are omnipotent and, judging by \nthe world \nthey created, not good\nor they are good, but the world slipped from their hands, \nand so they are not omnipotent.\nThe School of Epicurus\n \nSix years old, I felt horror at the stony \norder of the world.\n \nLater on, in vain, I sought shelter \nin colorful pictures of birds\nwhen I was the round-faced \nsecretary of the Circle \nof Nature Lovers.\n \nCharles Darwin, a clergyman-to-be, with regret\nannounced\nhis theory of natural selection, for he saw\nthat \nit served the devil\'s theology.\nBy proclaiming the triumph of the strong and the defeat \nof the weak, which is and has always been the devil\'s program, \nwhich \nis why he is called the Prince of This World.\n \nEverything that creeps, runs, flies, and dies \nis an argument against the divinity of man.\n \nI turned to anti-nature, it means, to art, \nin order to build our home, along with others, out of the sounds \nof music and paint on canvas and the rhythms of speech.\n \nThreatened at every moment, we marked our \ndays \non a calendar of stone or of paper.\n \nReady to be caught by \na cold \nhand reaching out of the abyss to pull us down together with our \nunfinished task.\n \nYet we believed that some of us had received a gift, \na grace, \nto spite the force of gravity.',
			imagesDir: 'argument-against-the-divinity-of-men/',
			photos: [
				"Poznań, Poland, 2017",
				"Gdynia, Poland, 2016",
				"Amsterdam, Holand, 2016",
				"Poznań, Poland, 2016",
				"Jerusalem, Israel, 2016",
				"Jerusalem, Israel, 2016",
				"Poznań, Poland, 2017",
				"Skoki, Poland, 2017",
				"Wieleń Pomorski, Poland, 2016",
				"Jerusalem, Israel, 2016",
				"Tel Aviv, Israel, 2016",
				"Poznań, Poland 2016",
				"London, Great Britain, 2016",
				"Malmo, Norway, 2016",
				"Poznań, Poland 2017",
				"Warsaw, Poland 2017",
				"Skoki, Poland 2017",
				"Jerusalem, Israel, 2016",
				"Borówiec, Poland 2017",
				"Tel Aviv, Israel, 2016",
				"Brussels, Belgium, 2017",
				"Poznań, Poland 2017",
				"Puszcza Notecka, Poland 2015",
				"A, Norway, 2016",
				"Skoki, Poland 2017",
				"Poznań, Poland 2017",
				"A, Norway, 2016",
				"Jerusalem, Israel, 2016",
				"Sudety, Poland, 2016",
				"Chomiąża Szlachecka, Poland, 2016",
				"Sudety, Poland, 2016",
				"Gdynia, Poland, 2016",
				"Norway, 2016",
				"Poznań, Poland, 2016",
				"Skoki, Poland, 2017",
				"Poznań, Poland, 2017",
				"Norway, 2016",
				"Lofoten, Norway, 2016",
				"Poznań, Poland, 2016",
				"Chomiąża Szlachecka, Poland, 2016",
				"Chomiąża Szlachecka, Poland, 2016",
				"Skoki, Poland, 2017",
				"Berlin, Germany, 2016",
				"Jerusalem, Israel, 2016",
				"Jerusalem, Israel, 2016",
				"A, Norway, 2016",
				"A, Norway, 2016",
				"Grenoble, France, 2016",
				"Poznań, Poland, 2015",
				"Skoki, Poland, 2017",
				"Skoki, Poland, 2017",
				"Skoki, Poland, 2017",
				"Skoki, Poland, 2017",
				"Poznań, Poland, 2017",
				"Poznań, Poland, 2016",
				"Brussels, Belgium, 2017",
				"Mechelen, Belgium, 2017",
				"Mechelen, Belgium, 2017"
			]
		},
		"lancuch-swiatla":  {
			title: 'Protest against judiciary overhaul',
			description: 'In summer of 2017, Law and Justice - conservative and socialist party rulling in Poland tried to pass the bill, witch objective was to overhaul juridical system in Poland. Due to the serious threat to separation of powers, thousends of protesters gathered every evening in a week, in witch parliment was discussing and voting.\n\nEventually bill passed in congress, but president Andrzej Duda decided to partially veto it.',
			imagesDir: 'lancuch-swiatla/',
			photos: [
				'Poznań, 20.07.2017',
				'Poznań, 20.07.2017',
				'Poznań, 20.07.2017',
				'Poznań, 20.07.2017',
				'Poznań, 20.07.2017',
				'Poznań, 20.07.2017',
				'Poznań, 20.07.2017',
				'Poznań, 20.07.2017',
				'Poznań, 20.07.2017',
				'Poznań, 20.07.2017',
				'Poznań, 23.07.2017',
				'Poznań, 23.07.2017',
				'Poznań, 20.07.2017',
				'Poznań, 20.07.2017',
				'Wrocław, 21.07.2017',
				'Poznań, 20.07.2017',
				'Poznań, 20.07.2017',
				'Poznań, 23.07.2017',
				'Wrocław, 21.07.2017',
				'Wrocław, 21.07.2017',
				'Wrocław, 21.07.2017',
				'Wrocław, 21.07.2017',
				'Wrocław, 21.07.2017',
				'Poznań, 20.07.2017',
				'Wrocław, 21.07.2017',
				'Poznań, 23.07.2017',
				'Poznań, 23.07.2017',
				'Poznań, 23.07.2017',
				'Wrocław, 21.07.2017',
				'Poznań, 23.07.2017',
				'Poznań, 23.07.2017',
				'Poznań, 23.07.2017',
				'Poznań, 20.07.2017',
				'Poznań, 23.07.2017',
				'Poznań, 23.07.2017',
				'Poznań, 23.07.2017',
				'Poznań, 23.07.2017',
				'Poznań, 23.07.2017',
				'Poznań, 23.07.2017',
				'Poznań, 23.07.2017'
			]
		}
}